version: '3.5'

networks:
  rede:

services:

  db:
    image: likesistemas/mysql-client:latest
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=eichefe_backend-tests
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dump.sql:/sql/dump.sql
    networks: 
      - rede
    depends_on: 
      - mysql

  mysql:
    image: mysql:5.5
    command: --innodb-use-native-aio=0
    ports:
      - 4010:3306
    environment:
      - MYSQL_DATABASE=eichefe_backend
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Fortaleza
    networks:
      - rede