name: ci-cd

on:
  push:
    branches:
      - master

  pull_request:

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker-compose up --build -d

  cd:
    needs: ci

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: likesistemas/mysql-client:latest

      - name: Image digest
        run: |
         echo "IMAGE: ${{ steps.docker_build.outputs.digest }}"
